### ISSUE TITLE
require placed on the wrong place

### ISSUE THREAD

**Issue by gabrielpoca** [groupbuddies/headquarters-ruby#14]
Like we found out yesterday, the require for the endpoints module is done on the wrong place. Right now it's on the [members.rb](https://github.com/groupbuddies/headquarters-ruby/blob/edc50b96f6128eb85ca9766ec8f35b7016038990/lib/headquarters/client/members.rb#L1) but it's used in other places, not only on this file.

**Comment by naps62** [comment]
thanks for submitting this :+1:
